# .goreleaser.yaml
version: 2

project_name: kiroku

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/kiroku
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Generate .deb and .rpm packages
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}"
    homepage: https://github.com/apolos666/kiroku
    description: "A lightweight, terminal-based note-taking application"
    maintainer: "Tran Duc Quang <tranducquang.apolos@gmail.com>"
    license: "MIT"
    formats:
      - deb
      - rpm

    # Dependencies (if any)
    # dependencies:
    #   - git

# Create a Homebrew tap (optional, requires a separate repo)
brews:
  - repository:
      owner: tranducquang
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    # TAP repository should be created first: https://github.com/tranducquang/homebrew-tap
    # If you don't have it yet, you can comment this block out or create the repo.

    directory: Formula
    homepage: "https://github.com/tranducquang/kiroku"
    description: "A lightweight, terminal-based note-taking application"
    license: "MIT"

release:
  github:
    owner: tranducquang
    name: kiroku
  draft: false
  prerelease: auto
